// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2BVV664PA4cgdco_Gxj2z3F7uUJWRQ-o',
    appId: '1:79452506986:android:b416db6524bbc0039db313',
    messagingSenderId: '79452506986',
    projectId: 'kpharmaapp-5a56d',
    storageBucket: 'kpharmaapp-5a56d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0mzYnZugfXdORXH8CC68kwDLCO3Pbu9I',
    appId: '1:79452506986:ios:13a4b1404d0e389b9db313',
    messagingSenderId: '79452506986',
    projectId: 'kpharmaapp-5a56d',
    storageBucket: 'kpharmaapp-5a56d.appspot.com',
    androidClientId: '79452506986-hu3l2mrrulak8tbcegqk1shf0mot1kta.apps.googleusercontent.com',
    iosClientId: '79452506986-vc27ra0pecopcg32rk3g9gb7s3qsspsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );
}
